### PR TITLE
First example comment is fucked

### PR DESCRIPTION
**Pull request by VincentCasse**
And token is bad generated with the link :(

### CODE REVIEW

**Comment by yadutaf** [comment]
LGTM. The pattern based ACL is powerful but a bit misleading. Maybe we could provide helpers in the wrappers to generate the rules. Like "RO access on all /web". Or " Full access to billing info". Or "Admin access on domain foo.com only"

**Comment by VincentCasse** [comment]
Not easy to handle in the code. You want to define "human features" on a lot of api endpoints. I'm afraid to end the works with a big hash of rules for each human feature as key.

I think we need to improve our docs a lot to have rights rules asked :)

**Comment by yadutaf** [comment]
I agree on the documentation aspect. Maybe we can just create a ovh.github.io/api-documentation github page and work from there.

About the generation, I think, we can be smart. For example, we can easily map
- Read Only: GET
- Read Write: GET, POST, PUT, DELETE

And add a "recursive" option on a helper. If set, it would automatically derive the pattern from a prefix.

For example, in the SMS scenario:

``` python
>>> generate_grant_request('/sms', recurse=True, rw=True)
GET /sms /sms/*
POST /sms /sms/*
PUT /sms /sms/*
DELETE /sms /sms/*

>>> generate_grant_request('/sms/account-1', recurse=True, rw=False)
GET /sms/account-1 /sms/account-1/*
```

ping @gregdel who created a helper for golang

**Comment by VincentCasse** [comment]
Indeed, it could be a good idea to implement everywhere!

Be warned: POST /sms, PUT /sms and DELETE /sms don't exist

Back on this pr : who merge it? :)

**Comment by yadutaf** [comment]
@golgeek. When the commit is signed ^^

**Comment by VincentCasse** [comment]
Done :)

**Comment by VincentCasse** [comment]
Up :)

**Comment by golgeek** [comment]
Done, sorry for the delay

**Comment by VincentCasse** [comment]
Thx :)

**Pull request merged**
