### PR TITLE
Update OVH API to 2.0.x

### PR DESCRIPTION
**Pull request by dsferruzza**
Hi!

This PR upgrades the dependency on the `ovh/ovh` package to its last version.
This allows to have Guzzle 6.x and solves #13.

It tested the package before *and* after this commit (using the example code in the README and real credentials). I got similar results in both cases so it seems to work!

I hope you will merge it and tag a new version (even a pre-release would help!).
Let me know if I can do something more.

### CODE REVIEW

**Comment by benjamineukles** [comment]
+1, I definitively need it. Can anyone tell me when this will be merged into the master?

**Comment by kblais** [comment]
@benjamineukles hope it will be merged soon... Needing this for a Laravel project with Guzzle 6...

**Comment by benjamineukles** [comment]
@kblais as noticed by @dsferruzza you can use his fork here #13

**Comment by kblais** [comment]
@benjamineukles Yeah, that's what we're gonna do while the PR is not merged, but using the "official" version up to date is still the best :)

**Comment by nWidart** [comment]
Any news on this?

**Comment by AClavijo** [comment]
Any news on this?

**Comment by Maxeee09** [comment]
+1 Need it !

**Pull request merged**
