### PR TITLE
doc: Add an example for specifying a sender

### PR DESCRIPTION
**Pull request by golgeek**
Signed-off-by: Ludovic Leroux ludovic.leroux@corp.ovh.com

### CODE REVIEW

**Comment by yadutaf** [comment]
In the first example, what will the recipient see as a sender number if we don't specify one explicitly ?

**Comment by golgeek** [comment]
He will see a random short code as a sender.

**Comment by yadutaf** [comment]
Alright. May be worth mentioning it in the example ? Aside from this, LGTM.

**Comment by golgeek** [comment]
Mention added :)

**Comment by golgeek** [comment]
Thx

**Pull request merged**
